version: '3.5'
services:
  app:
    image: ${IMAGE_NAME}:${IMAGE_TAG}
    build: .
  sut:
    image: mjanaki/php-nginx-alpine
    depends_on:
      - app
    command: /tmp/run_tests.sh
    volumes:
      - "./run_tests.sh:/tmp/run_tests.sh:ro"
